CREATE DATABASE IF NOT EXISTS `${DB_DATABASE_NAME}`
  CHARACTER SET = 'utf8mb4'
  COLLATE = 'utf8mb4_unicode_520_ci';

CREATE USER IF NOT EXISTS '${DB_USER_NAME}'@'${DB_HOST}'
  IDENTIFIED BY '${DB_USER_PASSWORD}';

REVOKE ALL PRIVILEGES, GRANT OPTION
  FROM '${DB_USER_NAME}'@'${DB_HOST}';

GRANT
  SELECT, INSERT, UPDATE, DELETE, CREATE,
  DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES,
  CREATE VIEW, SHOW VIEW, TRIGGER
ON
  `${DB_DATABASE_NAME}`.* TO '${DB_USER_NAME}'@'${DB_HOST}';

FLUSH PRIVILEGES;
