name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy locally on NAS
        run: |
          cd ${{ secrets.SSH_TARGET_FOLDER }}
          git fetch
          git pull
          docker-compose pull
          docker-compose up -d --force-recreate
